#!/bin/sh
# html上でalive nodes を取得

filealive=$(mktemp)
trap "rm $filealive" 0 1 2 3 15
/usr/sbin/fping -admq -t 50 -i 10 -r 1 -f /home/web/html/tmp/ping.dat >$filealive
cat $filealive | sed -z 's/\n/\<br \/\>/g'
