#!/bin/sh
# html上でdown nodes を取得

filedown=$(mktemp)
trap "rm $filedown" 0 1 2 3 15
/usr/sbin/fping -qum -t 50 -i 10 -r 1 -f /home/web/html/tmp/ping.dat >$filedown
cat $filedown | sed -z 's/\n/\<br \/\>/g'
